Enhance validate-catalog workflow with artifact upload and auto-update functionality

diff --git a/.github/workflows/validate-catalog.yaml b/.github/workflows/validate-catalog.yaml
--- a/.github/workflows/validate-catalog.yaml
+++ b/.github/workflows/validate-catalog.yaml
@@ -11,12 +11,17 @@ on:
   schedule:
     - cron: "0 0 * * *" # every day at midnight
 
+permissions:
+  contents: write
+  pull-requests: write
+
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
 jobs:
-  validate:
+  validate-and-generate:
+    timeout-minutes: 10
     runs-on: ubuntu-latest
     defaults:
       run:
@@ -35,3 +40,48 @@ jobs:
       - name: display catalog
         run: |
           cat output/consolidated-web-catalog.json | jq
+
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: consolidated-web-catalog.json
+          path: output/consolidated-web-catalog.json
+
+  update:
+    needs: validate-and-generate
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash -l {0}
+
+    environment:
+      name: ${{ github.event.pull_request.number }}
+      url: ${{ format('https://catalog.leap.columbia.edu/?catalog=https://raw.githubusercontent.com/{0}/{1}/catalog/output/consolidated-web-catalog.json', github.event.pull_request.head.repo.full_name, github.head_ref) }}
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          repository: ${{ github.event.pull_request.head.repo.full_name }}
+          ref: ${{ github.event.pull_request.head.ref }}
+          fetch-depth: 0
+          # ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
+
+      - name: Pull Remote Changes
+        run: |
+          git pull origin ${{ github.event.pull_request.head.ref }} --rebase --autostash
+
+      - uses: actions/download-artifact@v4
+        with:
+          name: consolidated-web-catalog.json
+          path: output
+
+      - name: Commit and Push
+        run: |
+          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+          git config --global user.name "github-actions[bot]"
+          python -m pip install pre-commit
+          pre-commit install
+          git add output/consolidated-web-catalog.json
+          # run pre-commit and return 0 to avoid failing the job
+          pre-commit run || true
+          git add output/consolidated-web-catalog.json || true
+          git commit -m "Auto-update consolidated-web-catalog.json" || true
